### ISSUE TITLE
Exception error for key and id

### ISSUE THREAD

**Issue by MadisonH-md** [whistlebee/awis-py#1]
access_key_id = getpass.getpass('Enter access key id: ')
secret_access_key = getpass.getpass('Enter secret access key: ')
I wonder what this parameter is for? I enter my AWS id and AWIS API KEY but get an exception error
Thx!

**Comment by whistlebee** [comment]
Hi there, thanks for raising the issue!
The secret access key is tied to the IAM user and is hidden after initial creation. This [link](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys) has more information on this.
If you don't have one already, go to the [management console](https://console.aws.amazon.com/iam/home#/users) and create a new user with __Programmatic Access__ and it'll give you the `AccessKeyId` and `SecretKey` to with this package (or any others).

Feel free to let me know if you need any help!

**Comment by MadisonH-md** [comment]
Hi, thanks for helping!

I did find out the access key and id. But after testing with them, I still got this exception error. Is there anything else I need to do? Thanks!
![error](https://user-images.githubusercontent.com/69473872/92335456-14d3a800-f065-11ea-89a5-da168359a68e.png)

**Comment by whistlebee** [comment]
From what I can see, you're doing everything correctly but I can't seem to reproduce the same error.
I've updated the code (after three years!) which fixes the `exception_handler` error to see what the underlying issue is.
Also, you'll be able to install it from PyPi now with:
`pip install awis-py`
Could you try again with the updated code and show the error produced?

**Comment by MadisonH-md** [comment]
Thank you whistlebee! It works now!

**Comment by whistlebee** [comment]
No problem @MadisonH-md glad I could help
